version: "3.3"

services:
  backend:
    build:
      context: ./backend
    image: chitweb_prod_backend

  frontend:
    build:
      context: ./frontend
    image: chitweb_prod_frontend
    ports:
      - "0.0.0.0:80:80"
