"""added nullable to some columns in Members-table

Revision ID: 54015a58b338
Revises: 09cd9fd02e5c
Create Date: 2021-07-11 19:11:34.629468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54015a58b338'
down_revision = '09cd9fd02e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
