"""add foreign key to users table

Revision ID: 3c30f97cc835
Revises: 7532b0d05fa8
Create Date: 2022-02-26 04:15:32.253692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c30f97cc835'
down_revision = '7532b0d05fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('specialization', sa.Integer(), nullable=False))
    op.create_foreign_key('fkey_specialization_user', 'users', 'specializations', ['specialization'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_specialization_user', 'users', type_='foreignkey')
    op.drop_column('users', 'specialization')
    # ### end Alembic commands ###
