"""add table specialization

Revision ID: b36c87f30df2
Revises: af614298b4f9
Create Date: 2022-02-22 20:44:07.218828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b36c87f30df2'
down_revision = 'af614298b4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialization_id'), 'specialization', ['id'], unique=False)
    op.create_index(op.f('ix_specialization_name'), 'specialization', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('short_bio', sa.String(), nullable=True),
    sa.Column('long_bio', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.drop_index('ix_User_first_name', table_name='User')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_index('ix_User_last_name', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('telegram', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_index('ix_User_last_name', 'User', ['last_name'], unique=False)
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_index('ix_User_first_name', 'User', ['first_name'], unique=False)
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_specialization_name'), table_name='specialization')
    op.drop_index(op.f('ix_specialization_id'), table_name='specialization')
    op.drop_table('specialization')
    # ### end Alembic commands ###
